[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

[etherscan]
arbitrum = { key = "${ARBISCAN_API}" }

[rpc_endpoints]
arbitrum = "${RPC_ARBITRUM}"

[fmt]
line_length = 160
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
wrap_comments = true